import { normalizeTechnology } from './package-technologies'

// Maps GitHub repository topics to technology labels. Topics are
// owner-curated metadata on the repository listing, so they surface stacks
// that language data and manifest files cannot see (deploy targets,
// integrations, frameworks buried in workspace manifests). Keys are
// normalized topic names; unmapped topics are ignored rather than guessed.
const TOPIC_TECHNOLOGIES: Record<string, string> = {
  // Languages
  typescript: 'TypeScript',
  javascript: 'JavaScript',
  python: 'Python',
  golang: 'Go',
  rust: 'Rust',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  ruby: 'Ruby',
  php: 'PHP',
  c: 'C',
  cpp: 'C++',
  cplusplus: 'C++',
  csharp: 'C#',
  fsharp: 'F#',
  dart: 'Dart',
  scala: 'Scala',
  elixir: 'Elixir',
  erlang: 'Erlang',
  clojure: 'Clojure',
  haskell: 'Haskell',
  lua: 'Lua',
  julia: 'Julia',
  perl: 'Perl',
  ocaml: 'OCaml',
  zig: 'Zig',
  nim: 'Nim',
  assembly: 'Assembly',
  fortran: 'Fortran',
  bash: 'Bash',
  powershell: 'PowerShell',
  r: 'R',
  // Frameworks and UI
  react: 'React',
  reactjs: 'React',
  nextjs: 'Next.js',
  vue: 'Vue',
  vuejs: 'Vue',
  nuxt: 'Nuxt',
  nuxtjs: 'Nuxt',
  svelte: 'Svelte',
  sveltekit: 'SvelteKit',
  angular: 'Angular',
  astro: 'Astro',
  gatsby: 'Gatsby',
  remix: 'Remix',
  solidjs: 'Solid',
  qwik: 'Qwik',
  emberjs: 'Ember',
  jquery: 'jQuery',
  alpinejs: 'Alpine.js',
  reactnative: 'React Native',
  expo: 'Expo',
  flutter: 'Flutter',
  electron: 'Electron',
  tauri: 'Tauri',
  capacitor: 'Capacitor',
  ionic: 'Ionic',
  tailwind: 'Tailwind CSS',
  tailwindcss: 'Tailwind CSS',
  bootstrap: 'Bootstrap',
  sass: 'Sass',
  materialui: 'Material UI',
  chakraui: 'Chakra UI',
  // NextUI was renamed HeroUI; both spellings resolve to the current name.
  heroui: 'HeroUI',
  nextui: 'HeroUI',
  shadcnui: 'shadcn/ui',
  styledcomponents: 'styled-components',
  // Client libraries and state
  reactrouter: 'React Router',
  redux: 'Redux',
  zustand: 'Zustand',
  mobx: 'MobX',
  tanstack: 'TanStack',
  tanstackrouter: 'TanStack Router',
  tanstackquery: 'TanStack Query',
  tanstacktable: 'TanStack Table',
  tanstackform: 'TanStack Form',
  tanstackstart: 'TanStack Start',
  reactquery: 'TanStack Query',
  trpc: 'tRPC',
  graphql: 'GraphQL',
  axios: 'Axios',
  socketio: 'Socket.IO',
  // Backends and runtimes
  nodejs: 'Node.js',
  deno: 'Deno',
  bun: 'Bun',
  express: 'Express',
  expressjs: 'Express',
  fastify: 'Fastify',
  nestjs: 'NestJS',
  django: 'Django',
  flask: 'Flask',
  fastapi: 'FastAPI',
  rails: 'Rails',
  rubyonrails: 'Rails',
  laravel: 'Laravel',
  spring: 'Spring',
  springboot: 'Spring Boot',
  dotnet: '.NET',
  aspnet: 'ASP.NET',
  wordpress: 'WordPress',
  // Data stores and platforms
  postgresql: 'PostgreSQL',
  postgres: 'PostgreSQL',
  mysql: 'MySQL',
  mariadb: 'MariaDB',
  sqlite: 'SQLite',
  mongodb: 'MongoDB',
  redis: 'Redis',
  elasticsearch: 'Elasticsearch',
  rabbitmq: 'RabbitMQ',
  supabase: 'Supabase',
  firebase: 'Firebase',
  neon: 'Neon',
  upstash: 'Upstash',
  prisma: 'Prisma',
  drizzle: 'Drizzle ORM',
  mongoose: 'Mongoose',
  sanity: 'Sanity',
  // Build and test tooling
  vite: 'Vite',
  vitejs: 'Vite',
  vitest: 'Vitest',
  jest: 'Jest',
  playwright: 'Playwright',
  cypress: 'Cypress',
  webpack: 'Webpack',
  babel: 'Babel',
  eslint: 'ESLint',
  storybook: 'Storybook',
  maven: 'Maven',
  gradle: 'Gradle',
  cmake: 'CMake',
  makefile: 'Make',
  // DevOps, hosting, and delivery
  docker: 'Docker',
  dockercompose: 'Docker Compose',
  kubernetes: 'Kubernetes',
  k8s: 'Kubernetes',
  terraform: 'Terraform',
  ansible: 'Ansible',
  jenkins: 'Jenkins',
  githubactions: 'GitHub Actions',
  gitlab: 'GitLab',
  vercel: 'Vercel',
  netlify: 'Netlify',
  cloudflare: 'Cloudflare',
  heroku: 'Heroku',
  flyio: 'Fly.io',
  railway: 'Railway',
  render: 'Render',
  aws: 'AWS',
  amazonwebservices: 'AWS',
  azure: 'Azure',
  gcp: 'Google Cloud',
  googlecloud: 'Google Cloud',
  helm: 'Helm',
  vagrant: 'Vagrant',
  serverless: 'Serverless',
  // AI providers and tooling
  openai: 'OpenAI',
  gemini: 'Gemini',
  googlegemini: 'Gemini',
  anthropic: 'Anthropic',
  langchain: 'LangChain',
  // Static site generators and games
  jekyll: 'Jekyll',
  hugo: 'Hugo',
  eleventy: 'Eleventy',
  unity: 'Unity',
  unrealengine: 'Unreal Engine',
  godot: 'Godot',
  threejs: 'Three.js',
}

export function technologiesFromTopics(topics: string[]) {
  const technologies = new Set<string>()
  for (const topic of topics) {
    const technology = TOPIC_TECHNOLOGIES[normalizeTechnology(topic)]
    if (technology) technologies.add(technology)
  }
  return Array.from(technologies)
}
