import Link from 'next/link'
import { Logo } from '@/components/icons/Logo'
import { createClient } from '@/utils/supabase/server'

export const metadata = { title: 'Privacy and data use · Proofstack' }

export default async function PrivacyPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const destination = user ? { href: '/', label: 'Dashboard' } : { href: '/login', label: 'Sign in' }

  return (
    <div className="min-h-screen font-sans">
      <header className="border-b border-line bg-ink/90">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-4 py-3 sm:px-6">
          <Link href="/" className="flex items-center gap-3">
            <Logo className="h-5 w-5 text-brand" />
            <span className="label font-bold tracking-[0.3em]">Proofstack</span>
          </Link>
          <nav aria-label="Privacy navigation" className="flex items-center gap-4">
            <Link href="/help" className="eyebrow inline-flex min-h-10 items-center text-dim transition-colors hover:text-foreground">Help</Link>
            <Link
              href={destination.href}
              className="inline-flex min-h-10 items-center border border-brand-dim bg-brand px-3 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-on-brand transition-colors hover:bg-brand/90"
            >
              {destination.label}
            </Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-3xl space-y-8 px-4 py-10 sm:px-6">
        <h1 className="text-2xl font-semibold tracking-tight">Privacy and data use</h1>

        <section className="space-y-3">
          <h2 className="label text-dim">GitHub access</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            Sign-in uses GitHub OAuth with read-only scopes (<code className="font-mono text-[12px]">public_repo</code>, <code className="font-mono text-[12px]">read:user</code>, <code className="font-mono text-[12px]">user:email</code>). Proofstack reads your public repository metadata, root manifests, and language data. If you choose to include private repositories, you can grant the <code className="font-mono text-[12px]">repo</code> scope from your dashboard; it is never requested at sign-in.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="label text-dim">What is stored</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            Proofstack stores repository metadata (names, descriptions, languages, detected technologies), README excerpts you explicitly index, the project briefs you write, and generated portfolio briefings. Your GitHub token is encrypted with AES-256-GCM and stored server-side only.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="label text-dim">AI processing</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            Briefings, chat answers, and embeddings are generated by Google Gemini. Public repository metadata and your own notes are sent to Gemini when you use those features. Private repository content is sent only after you enable AI processing for that specific repository, and you can withdraw consent at any time, which removes its embedded README evidence.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="label text-dim">Automated previews</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            For GitHub users who have not published a Proofstack profile, visitors can request a clearly labeled automated preview generated by Google Gemini from public GitHub data only. Previews are temporary, cached for up to 24 hours, and never include private data or owner content. Signed-in owners can exclude their GitHub username from the account page.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="label text-dim">Caching</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            Upstash Redis caches GitHub responses, rate limits, and processing leases, isolated per user and per token. Public lookups for automated previews share a per-username cache with no account data.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="label text-dim">Your notes and AI output</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            Project briefs are your own statements. Generated output is an AI interpretation labeled as such and is never presented as verified fact. Owner-reviewed content is never silently overwritten by regeneration or syncs.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="label text-dim">Account deletion</h2>
          <p className="text-sm leading-relaxed text-foreground/90">
            You can delete your account from the <Link href="/account" className="text-brand hover:underline">account page</Link>. Deletion removes your profile, projects, briefs, briefings, embeddings, and stored GitHub credential.
          </p>
        </section>

        <section className="space-y-3 border-t border-line pt-6">
          <p className="text-sm leading-relaxed text-dim">
            Proofstack is provided as-is, without a formal terms of service. Questions or requests can be sent through the <a href="https://github.com/jrudman25/Repfolio" target="_blank" rel="noreferrer" className="text-brand underline-offset-2 hover:underline">project&apos;s GitHub repository<span className="sr-only"> (opens in a new tab)</span></a>.
          </p>
        </section>
      </main>
    </div>
  )
}
